### PR TITLE
#149 - Exception logging in LoggingSlice

### LINKED ISSUE #149: `LoggingSlice` should log errors
If exception is thrown on attempt to handle request by slice `LoggingSlice` does not log anything. This makes it hard to understand problems in faulty slices. It should be logging exceptions as it logs success responses.

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #149 
Added exception logging to `LoggingSlice`

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#150](https://github.com/artipie/http/issues/150) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/db033f3d-095a-41f8-8ec4-6fdba3fd2103); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

File: src/main/java/com/artipie/http/slice/LoggingSlice.java [hunk 1]
```diff
@@ -81,8 +87,33 @@ public Response response(
         final StringBuilder msg = new StringBuilder(">> ").append(line);
         LoggingSlice.append(msg, headers);
         Logger.log(this.level, this.slice, msg.toString());
-        return connection -> this.slice.response(line, headers, body)
-            .send(new LoggingConnection(connection));
+        return connection -> {
```
Comment (paulodamaso) [inline src/main/java/com/artipie/http/slice/LoggingSlice.java:90]: @olegmoz Wouldn't we be loggin the exception twice in this case (one in line 96 and another in 103)?

File: src/main/java/com/artipie/http/slice/LoggingSlice.java [hunk 2]
```diff
@@ -81,8 +87,33 @@ public Response response(
...
+            }
+        };
+    }
+
+    /**
+     * Writes throwable to logger.
+     *
+     * @param throwable Throwable to be logged.
+     */
+    private void log(final Throwable throwable) {
```
Comment (paulodamaso) [inline src/main/java/com/artipie/http/slice/LoggingSlice.java:113]: @olegmoz How about creating a new class, `Logged`? We could reuse it in all other slices, and it would be easier to unit test it

File: src/test/java/com/artipie/http/slice/LoggingSliceTest.java [hunk 3]
```diff
@@ -61,4 +67,63 @@ void shouldLogRequestAndResponse() {
             (status, headers, body) -> CompletableFuture.allOf()
         ).toCompletableFuture().join();
     }
+
+    @Test
+    void shouldLogAndPreserveExceptionInSlice() {
```
Comment (paulodamaso) [inline src/test/java/com/artipie/http/slice/LoggingSliceTest.java:72]: @olegmoz I don't see the utility of these tests; we are not assuring that the exception was logged. How about:
- extract the private log method to a new class (see above)
- make this class receive a `writer`
- execute the `LoggingSlice`with error and check if the error log was appended to the writer

File: src/main/java/com/artipie/http/slice/LoggingSlice.java (hunk 1 above)
Comment (olegmoz) [reply src/main/java/com/artipie/http/slice/LoggingSlice.java:90]: @paulodamaso no, that won't happen. These two cases for different cases of errors: thrown in sync code or returned normally as completion stage

File: src/test/java/com/artipie/http/slice/LoggingSliceTest.java (hunk 3 above)
Comment (olegmoz) [reply src/test/java/com/artipie/http/slice/LoggingSliceTest.java:72]: @paulodamaso I do not agree that these tests are useless, it is important that errors are not getting consumed by this slice. Though that's true, that main functionality of this class is not tested. There was discussion about it when this class was first created, and we agreed that testing it does not worth the effort of mocking logging system.

Also providing the logging method in constructor will make usage of this class harder. That is why logging is done by static methods everywhere.

File: src/main/java/com/artipie/http/slice/LoggingSlice.java (hunk 2 above)
Comment (olegmoz) [reply src/main/java/com/artipie/http/slice/LoggingSlice.java:113]: @paulodamaso sorry, I do not like the idea. `Logged` does not make much sense to me and looks like artificial way to provide `log` method implementation

File: src/main/java/com/artipie/http/slice/LoggingSlice.java [hunk 4]
```diff
@@ -81,8 +87,33 @@ public Response response(
...
-            .send(new LoggingConnection(connection));
+        return connection -> {
+            try {
+                return this.slice.response(line, headers, body)
+                    .send(new LoggingConnection(connection))
+                    .exceptionally(
+                        throwable -> {
+                            this.log(throwable);
+                            Throwables.throwIfUnchecked(throwable);
+                            throw new CompletionException(throwable);
```
Comment (g4s8) [inline src/main/java/com/artipie/http/slice/LoggingSlice.java:98]: @olegmoz why `CompletionException` here? According to [the javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionException.html), it can be
>  thrown when an error or other exception is encountered in the course of completing a result or task

But this `throwable` can be propagated from underlying slice error.

File: src/main/java/com/artipie/http/slice/LoggingSlice.java [hunk 5]
```diff
@@ -81,8 +87,33 @@ public Response response(
...
+
+    /**
+     * Writes throwable to logger.
+     *
+     * @param throwable Throwable to be logged.
+     */
+    private void log(final Throwable throwable) {
+        final StringWriter writer = new StringWriter();
+        throwable.printStackTrace(new PrintWriter(writer));
+        Logger.log(this.level, this.slice, "Failure: %s", writer.toString());
```
Comment (g4s8) [inline src/main/java/com/artipie/http/slice/LoggingSlice.java:116]: @olegmoz these 3 lines can be simplified to:
```java
Logger.log(this.level, this.slice, "Failure: %[exception]s", throwable);
```

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/http/issues/150#issuecomment-632641214))

@g4s8 This pull request [#150](https://github.com/artipie/http/issues/150) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fa12dc72-c461-43fc-8df1-2516caf518f2); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

File: src/main/java/com/artipie/http/slice/LoggingSlice.java (hunk 4 above)
Comment (olegmoz) [reply src/main/java/com/artipie/http/slice/LoggingSlice.java:98]: @g4s8 didn't think of way to propagate the throwable as is. Found a solution now

File: src/main/java/com/artipie/http/slice/LoggingSlice.java (hunk 5 above)
Comment (olegmoz) [reply src/main/java/com/artipie/http/slice/LoggingSlice.java:116]: @g4s8 simplified it, thanks!

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
